# Generated by Django 4.2.7 on 2025-05-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('spider_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_javascript', models.BooleanField(default=False)),
                ('requires_login', models.BooleanField(default=False)),
                ('requests_per_minute', models.IntegerField(default=10)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('items_scraped', models.IntegerField(default=0)),
                ('items_saved', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=50)),
                ('custom_settings', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scraper.scrapingsource')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('error_type', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_details', to='scraper.scrapingjob')),
            ],
        ),
    ]
