services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gamerecommender
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gamerecommender
      - REDIS_URL=redis://redis:6379/0
      # API keys for game data and images
      - RAWG_API_KEY=f8246cb2736247bd849cad48bab0caec  # Using a valid RAWG API key
      - IGDB_CLIENT_ID=  # Optional: Get from https://dev.twitch.tv/console/apps
      - IGDB_CLIENT_SECRET=  # Optional: Get from https://dev.twitch.tv/console/apps
      - SERP_API_KEY=  # Optional: Get from https://serpapi.com/

  celery:
    build: ./backend
    command: celery -A core worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gamerecommender
      - REDIS_URL=redis://redis:6379/0
      - RAWG_API_KEY=f8246cb2736247bd849cad48bab0caec
      - IGDB_CLIENT_ID=  # Optional: Get from https://dev.twitch.tv/console/apps
      - IGDB_CLIENT_SECRET=  # Optional: Get from https://dev.twitch.tv/console/apps
      - SERP_API_KEY=  # Optional: Get from https://serpapi.com/

  celery-beat:
    build: ./backend
    command: celery -A core beat -l info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gamerecommender
      - REDIS_URL=redis://redis:6379/0
      - RAWG_API_KEY=f8246cb2736247bd849cad48bab0caec
      - IGDB_CLIENT_ID=  # Optional: Get from https://dev.twitch.tv/console/apps
      - IGDB_CLIENT_SECRET=  # Optional: Get from https://dev.twitch.tv/console/apps 
      - SERP_API_KEY=  # Optional: Get from https://serpapi.com/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm start
    working_dir: /app
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data: 