# Generated by Django 4.2.7 on 2025-05-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('clicked', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='games.game')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.userprofile')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('user_profile', 'game')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('very_bad', 'Very Bad Recommendation'), ('bad', 'Bad Recommendation'), ('neutral', 'Neutral'), ('good', 'Good Recommendation'), ('very_good', 'Very Good Recommendation')], max_length=10)),
                ('has_played', models.BooleanField(blank=True, null=True)),
                ('interested', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommendations.gamerecommendation')),
            ],
        ),
    ]
