# Generated by Django 4.2.7 on 2025-05-13 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('has_played', models.BooleanField(default=True)),
                ('playtime_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='GenrePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.genre')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='PlatformPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.platform')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('hours_per_week', models.IntegerField(blank=True, null=True)),
                ('survey_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_games', models.ManyToManyField(blank=True, related_name='favorited_by', to='games.game')),
                ('preferred_genres', models.ManyToManyField(through='users.GenrePreference', to='games.genre')),
                ('preferred_platforms', models.ManyToManyField(through='users.PlatformPreference', to='games.platform')),
                ('rated_games', models.ManyToManyField(related_name='ratings', through='users.GameRating', to='games.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGamePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefers_multiplayer', models.BooleanField(blank=True, null=True)),
                ('prefers_competitive', models.BooleanField(blank=True, null=True)),
                ('prefers_cooperative', models.BooleanField(blank=True, null=True)),
                ('prefers_story_driven', models.BooleanField(blank=True, null=True)),
                ('prefers_open_world', models.BooleanField(blank=True, null=True)),
                ('prefers_linear', models.BooleanField(blank=True, null=True)),
                ('difficulty_preference', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('variable', 'Variable')], max_length=10)),
                ('willing_to_pay', models.CharField(blank=True, choices=[('free_only', 'Free Only'), ('under_20', 'Under $20'), ('under_60', 'Under $60'), ('any_price', 'Any Price')], max_length=20)),
                ('accepts_in_app_purchases', models.BooleanField(blank=True, null=True)),
                ('additional_preferences', models.TextField(blank=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_preferences', to='users.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='platformpreference',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='genrepreference',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='gamerating',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='platformpreference',
            unique_together={('user_profile', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='genrepreference',
            unique_together={('user_profile', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='gamerating',
            unique_together={('user_profile', 'game')},
        ),
    ]
